Feature/issue 14 create show place
f-lab-edu/culture-ticketing pull request #17
Opened 2023-11-08 07:40 UTC by joona95

Issue: #15

기능
- 공연 내 Embedded 클래스로 둔 장소 정보 도메인 분리
- 장소 등록 기능 추가
- 공연과 장소 다대일 연관관계 추가
- 공연 등록 시 장소 id 값 받아서 조회 후 저장하도록 수정

기타
- gitignore 재적용 (generated 폴더 제외)

(+)
이전에 작업하던 Issue-3정보가 필요하다보니 issue-3브랜치에서 새 브랜치를 생성해서 작업했습니다. 
이런 경우에 기존 PR이 유지되고 있는 경우엔 전체 커밋이 뜨는데 기존 PR이 완료된 이후에 PR을 올려야 하는걸까요?

2023-11-11 12:17 UTC, f-lab-moony commented
이전 작업에 의존성이 있는 경우라면 작업은 그렇게 진행하시되, PR은 끝나고 올리는게 나을 것 같아요 ~ 왜냐면 어차피 작업한걸 리베이스 해야될거라 ..

2023-11-11 12:24 UTC, f-lab-moony requested changes
고생하셨습니다 ~
코멘트를 좀 남겨 뒀는데 확인 부탁드려요!

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/common/response/BaseResponse.java
> +public class BaseResponse<T> {
api를 사용하는 클라이언트 입장에서, 성공시의 응답도 이렇게 감싸져 있는 건 별로 반기지 않을 것 같아요.
실패시에는 코드나 사유 등이 필요하겠지만, 성공시에는 어차피 보지도 않을건데 굳이 구조를 만들어놔야 하니까요. 구조에서 빼더라도 data를 한번 거쳐야 하는 ..?
어차피 성공/실패는 HTTP Status로 볼거라 .. 성공시엔 그냥 감싸지지 않은 객체를 던지는게 어떨까요 ?

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +        Place place = Place.builder()
요 만들어주는거 request 내부에 toEntity() 정도로 선언하는 건 어떨까요 ?

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/place/domain/Place.java
> +    @Column(name = "place_id", nullable = false, updatable = false)
컬럼은 전체 다 설정해주는게 좋을 것 같아요 ~

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/place/domain/Place.java
> +@Table(name = "PLACES")
요거 왜 대문자에요 ? + 테이블과 엔티티 클래스 이름이 왜 다른가요 ?

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/dto/ShowSaveRequest.java
> +    private String ageRestrictionCd;
이거 바로 enum으로 받아도 되지 않을까요 ?

2023-11-11 12:24 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/dto/ShowSaveRequest.java
> +    @NotBlank(message = "카테고리를 입력해주세요.")
유효성검사를 request에서만 잡고 서비스에서는 안하고 계신 것 같은데요, 만약 다른 개발자가 요청을 잘못 만들고 같은 서비스를 호출하면 잘못된 값 판별은 어떻게 하게 되나요 ?

2023-11-14 11:14 UTC, joona95 commented on src/main/java/com/culture/ticketing/common/response/BaseResponse.java
> +public class BaseResponse<T> {
그렇군요..! 응답값 감싸져 있는 구조 제거하고 수정했습니다! 
이전에 프로젝트하고 할 때 resultcode를 따로 정의해서 넘겨주기 위해 응답값 구조를 따로 만들어서 했던 걸 그냥 큰 고민 없이 가져다썼네요..!

2023-11-14 11:16 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +        Place place = Place.builder()
해당 부분 수정했습니다! [8265321](https://github.com/f-lab-edu/culture-ticketing/pull/17/commits/82653210d336bf0ffa47db64fc970353549e106c)
하면서 Show 생성 request에서도 추가했는데요. Show 클래스는 Place 클래스와는 다르게 연관관계가 있어서 placeId로 조회한 Place를 받아서 빌드하도록 했는데 괜찮을까요?

2023-11-14 11:17 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/domain/Place.java
> +    @Column(name = "place_id", nullable = false, updatable = false)
넵 수정완료했습니다! [0fb6fca](https://github.com/f-lab-edu/culture-ticketing/pull/17/commits/0fb6fcac3ab02ff41e69e571bbbd0fa442904656)

2023-11-14 11:20 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/domain/Place.java
> +@Table(name = "PLACES")
예전에 DB 테이블 네이밍 부분에서 대문자로 설정한다고 봤던 기억이 있어서 사실 큰 고민 없이 습관처럼 대문자 썼던 것 같아요. 보통 소문자를 사용하나요? 테이블명 지을 때 복수형을 습관처럼 썼어서 아무 생각 없이 클래스명과 다르게 했네요. 검색해보니 보통 단수형을 더 많이 쓰는군요..! 수정했습니다.
show는 예약어랑 겹치는 것 같아서 shows로 설정했습니다. [b81ec6c](https://github.com/f-lab-edu/culture-ticketing/pull/17/commits/b81ec6c55b352dae6eb1d6866844c7f09648403d)

2023-11-14 11:21 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/dto/ShowSaveRequest.java
> +    private String ageRestrictionCd;
아 그러게요! 수정했습니다! [0468ea8](https://github.com/f-lab-edu/culture-ticketing/pull/17/commits/0468ea81c41009e5e17d3240b56205cd7df775fc)

2023-11-14 11:27 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/dto/ShowSaveRequest.java
> +    @NotBlank(message = "카테고리를 입력해주세요.")
아하..! 요청값 유효성 검사를 서비스 내부에서도 처리해야겠군요. [9601123](https://github.com/f-lab-edu/culture-ticketing/pull/17/commits/96011233e21560eceeff9b20bbacaabe1e864220)
일단 이렇게 수정하긴 했는데 각 항목마다 메세지를 별개로 만들어서 예외를 각각 잡아줘야 하는 게 최선이 맞을까요? 유효성 검사 코드 부분이 너무 길어지지는 않나 싶기도 해서요..! 그렇다고 뭉뚱그려서 작성을 하면 어떤 오류인지 명확하지 않을 것 같고요. 아예 생성자 부분에서 생성 시 유효성 검사를 하는 게 낫나 싶기도 하고요..

2023-11-14 14:56 UTC, merged