Feature/issue 12 create show scehdule
f-lab-edu/culture-ticketing pull request #19
Opened 2023-11-20 14:43 UTC by joona95

Issue: #12 

기능

- 공연 일정 추가 기능
- 공연 클래스 내부의 공연 시작날짜 및 종료날짜 정보 제거
- 공연 일정 클래스 내에 공연 아이디값을 가지도록 추가 (하나의 공연에 여러 공연 일정을 가질 수 있음)
- 같은 공연 내에 중복 일정 생기지 않도록 검사

기타

- 장소 목록 조회 시 응답값 리턴 오류 수정
- 장소 목록 조회 시 요청값 유효성 검사 오류 수정
- 장소 목록 조회 시 offset 방식에서 more 방식 전환 (querydsl 활용)
- 생성자 내 유효성 검사 항목 추가
- ShowScheduleSaveRequest 클래스의 toEntity() 메서드에서 showScheduleTime 값의 초(second)가 0으로 고정되도록 처리하고 있는데 괜찮을지 고민됨

2023-11-25 15:12 UTC, f-lab-moony requested changes
고생하셨습니다 ~
코멘트를 좀 남겨 뒀는데 확인 한번 해보고 넘어가면 좋을 것 같아요 ~
확인 후 다시 푸시 해주세요!

2023-11-25 15:12 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +        placeService.getPlaceByPlaceId(request.getPlaceId());
해당 도메인의 아이디니까 그냥 getPlaceById 해도 될 것 같아요 ~ 저는 select나 find를 주로 쓰긴 합니다 뭔가 get은 갖고 있는걸 그냥 전달해주는 getter의 느낌이 강해서 ..

2023-11-25 15:12 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/dto/ShowScheduleSaveRequest.java
> +    private LocalDate showScheduleDate;
요거 그냥 합쳐서 LocalDateTime으로 써도 되지 않아요 ?

추가로, 특정 시간이 아니라 범위가 되어야 할 것 같은데 .. 지금 구조라면 11/26일 1시에 공연이 있는데 11/26일 1시 1분에도 공연 등록이 가능한거 아닌가요 ?

2023-11-26 06:57 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +        if (request.getLatitude() == null || request.getLatitude().compareTo(BigDecimal.ZERO) <= 0) {
아하 넵 수정했습니다! ([92ee1fe](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/92ee1fe87fbccaa999ba6482b39b76e192206d48))
훨씬 깔끔하게 유효성 검사 할 수 있네요..!

2023-11-26 06:57 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +        return placeRepository.findById(placeId).orElseThrow(PlaceNotFoundException::new);
넵 not found 인 경우 id값 메세지에 추가하도록 수정했습니다! ([3e661e6](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/3e661e646579429af9549e745dc8dd1dda7ca597))

2023-11-26 06:57 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/infra/PlaceRepositoryImpl.java
> +    private final EntityManager em;
아하 그렇겠네요..! 따로 클래스로 뺐습니다! ([e8998fa](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/e8998fabaf2da7e9ee3bc51d3b377ee3a0d2f44b))

2023-11-26 06:58 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/infra/PlaceRepositoryImpl.java
> +import static com.culture.ticketing.place.domain.QPlace.*;
넵 수정했습니다! ([04f8df5](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/04f8df5db30d66c485ca2e61a7ff1beba5ce2279))
IDE 설정에서도 안하도록 설정값 수정해뒀습니다!

2023-11-26 06:59 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowScheduleService.java
> +        if (request.getShowId() == null) {
아하 null여부를 DTO에서도 검사하고 있는데 서비스에도 해야하지 않을까 싶어서 추가했던거긴 합니다..!

2023-11-26 07:02 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowScheduleService.java
> +        showService.getShowByShowId(request.getShowId());
요청값으로 받은 공연 아이디값을 가진 공연이 있는지 여부를 체크한 후에 공연 일정 추가하도록 하고 싶어서 검사의 의미로 호출하는 부분이긴 합니다..! 따로 다른 메서드로 빼야 할까요?

2023-11-26 07:16 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/dto/ShowScheduleSaveRequest.java
> +    private LocalDate showScheduleDate;
그러게요..? 따로 저장하는 게 관리가 더 쉽지 않을까 싶었던 건데 사실 같이 저장해도 문제 없을 것 같네요.
공연 정보에 러닝타임 정보가 있어서 시작일시와 종료일시를 따로 받을 생각을 안했던 것 같아요. 
지금은 말씀하신대로 공연 일정 등록 시 1분 뒤 일시도 등록이 돼서 문제가 있네요. 공연 러닝타임 정보 활용해서 등록 시 체크를 추가하도록 하겠습니다.

2023-11-26 14:41 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +        placeService.getPlaceByPlaceId(request.getPlaceId());
get 대신 find 사용하도록 수정했습니다! ([c2b53c9](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/c2b53c91bcdb8b5cc85a42c0f4751b7cb3abdad0))

2023-11-26 14:53 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/dto/ShowScheduleSaveRequest.java
> +    private LocalDate showScheduleDate;
이 부분은 수정은 했는데 다시 한 번 확인부탁드려요..! ([81acb87](https://github.com/f-lab-edu/culture-ticketing/pull/19/commits/81acb87bb3e93e676d5d071c94429f891218e6a3))
1. 공연 일정의 날짜와 시간 합쳐서 받고 저장하도록 수정했습니다.
2. 그리고 중복 공연 일정 확인 시에 공연 러닝시간 활용하는 게 나을 것 같아서 등록된 일정을 시작시간으로 하고 해당 일정부터 러닝시간 내에 겹치는지 체크하도록 수정했습니다. 이렇게 괜찮을까요?

2023-11-26 14:54 UTC, joona95 commented
위에 코멘트 주신 부분들은 수정 완료했고 답글도 달아뒀습니다..! 확인 부탁드립니다 😊

2023-12-03 03:36 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/dto/ShowScheduleSaveRequest.java
> +    private LocalDate showScheduleDate;
1. 이전에 피드백 주신 대로 공연 정보에 공연 시작날짜, 종료 날짜 받고 러닝타임 정보 저장하도록 했습니다. 
2. 그리고 공연 일정 클래스는 회차 정보 클래스로 변경하였습니다. 회차 정보 등록 시에 시작 시간만 받고 공연 러닝타임으로 계산하여 회차 시작일시와 종료일시를 저장하도록 수정했습니다.
3. 회차 정보에 출연자 정보 저장을 위해서 공연의 출연자 정보 저장 클래스와 회차의 출연자 정보 저장 클래스를 추가했습니다. 매번 회차 등록 시 동일 출연자 정보를 매번 입력하는 건 비효율적일 것 같아서 공연마다 출연자 정보 등록을 따로 하도록 했습니다. 그 후 공연의 출연자 목록 중에서 회차 등록 시 회차 출연자 아이디 값 목록을 전달하도록 했습니다.

2023-12-03 03:37 UTC, joona95 commented
- 이전에 피드백 주신 대로 공연 정보에 공연 시작날짜, 종료 날짜 받고 러닝타임 정보 저장하도록 했습니다.
- 그리고 공연 일정 클래스는 회차 정보 클래스로 변경하였습니다. 회차 정보 등록 시에 시작 시간만 받고 공연 러닝타임으로 계산하여 회차 시작일시와 종료일시를 저장하도록 수정했습니다.
- 회차 정보에 출연자 정보 저장을 위해서 공연의 출연자 정보 저장 클래스와 회차의 출연자 정보 저장 클래스를 추가했습니다. 매번 회차 등록 시 동일 출연자 정보를 매번 입력하는 건 비효율적일 것 같아서 공연마다 출연자 정보 등록을 따로 하도록 했습니다. 그 후 공연의 출연자 목록 중에서 회차 등록 시 회차 출연자 아이디 값 목록을 전달하도록 했습니다.

2023-12-03 17:09 UTC, f-lab-moony approved these changes
고생하셨습니다!
크게 피드백 드릴 부분은 없는 것 같네요
바로 머지 하겠습니다 ~

2023-12-03 17:09 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/api/ShowController.java
> +    @PostMapping("/performers")
요렇게 복수로 표현되는건 자신의 도메인에 대해서만 사용하는 패턴이에요 ~
지금같은경우는 `/show/performers`가 될텐데, 이러면 어떤 도메인을 등록하려는건지 알기가 좀 힘들 것 같아요
추가로, performer라는 도메인이 생긴 것 같은데, 컨트롤러가 분리되는게 맞지 않을까요 ?

2023-12-03 17:09 UTC, merged