Feature/issue 4 retrieve shows
f-lab-edu/culture-ticketing pull request #20
Opened 2023-12-06 08:31 UTC by joona95

Issue: #4 

- 공연 목록 조회 기능 추가
- 공연 목록 more 방식으로 offset, size 받아서 조회하도록 처리
- 공연 목록 조회 시 카테고리별 검색 가능하도록 추가
- 공연별 출연자 목록 조회 기능 추가
- 출연자, 회차 관련 컨트롤러 분리

2023-12-07 14:32 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백을 좀 남겨 두었는데, 다음 작업 진행 전 한번 살펴보면 좋을 것 같아요!

2023-12-07 14:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/place/api/PlaceController.java
> +    public List<PlaceResponse> getPlaces(@RequestParam(name = "offset") Long offset,
요 위에 `@GetMapping` 에 특별한 경로 없으면 그냥 괄호부분은 지워도 될 것 같아요 ~

2023-12-07 14:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +    public List<Place> findByIdIn(List<Long> placeIds) {
약간 취향일수도 있긴 한데, 서비스에서 findByIdIn 으로 메서드명이 정해지는건 좀 역할에 안맞지 않나 하는 생각이 드네요!
In절로 조회를 하는건 어떻게 하는지에 대한 부분이라, Repository에 명시가 되는게 맞지 않나 싶어서요 ~

2023-12-07 14:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/api/RoundController.java
> +@RequestMapping("/rounds")
요거 꼭 그럴필욘 없긴 한데, api 제공시엔 api라고 명시해서 정적 리소스 서빙하는거랑 좀 차이를 두고, 버전을 명시해서 나중에 하위호환을 고려해놓는게 좋다고 저는 생각합니다..!

`api/v1/rounds` 같은 느낌 ..?

2023-12-09 12:42 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/api/PlaceController.java
> +    public List<PlaceResponse> getPlaces(@RequestParam(name = "offset") Long offset,
넵 수정완료했습니다 ! [2e3e718](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/2e3e7187fae5e7b65b0688457be264b43a8e7e01)

2023-12-09 12:43 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/application/PlaceService.java
> +    public List<Place> findByIdIn(List<Long> placeIds) {
아하 넵 수정했습니다! findPlacesByIds 정도로 바꿨습니다..! ([29f96eb](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/29f96eb0c8424397ee6e028f0167413f86318a8c))

2023-12-09 12:43 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/api/RoundController.java
> +@RequestMapping("/rounds")
넵 수정완료했습니다! ([a231817](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/a231817e06ce52610ba1892a9e934fbb2706ae7b))

2023-12-09 12:43 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +        Map<Long, Place> placeMapByPlaceId = placeService.findByIdIn(shows.stream()
넵 수정했습니다! ([817f384](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/817f384e9fd76342768df3d8a551d74f6b899496))

2023-12-09 12:44 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +                .collect(Collectors.toMap(Place::getPlaceId, place -> place));
아하 그런 게 있었군요! 수정했습니다! ([72eca2c](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/72eca2ce0085afbc191680bf02eab0e70b08e5fc))

2023-12-09 12:44 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +                .map(show -> ShowResponse.builder()
ShowResponse에 create 메서드 추가했습니다! ([09ea612](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/09ea612362da6ccf3e2cebfcbefd04f5fcbb36c4))

2023-12-09 12:45 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +                        .placeName(placeMapByPlaceId.get(show.getPlaceId()).getPlaceName())
아하 그렇겠네요! 예외처리 추가했습니다! ([b306c6f](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/b306c6f6336a888c9890203ac518b317720f6900))

2023-12-09 12:45 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/infra/ShowRepositoryImpl.java
> +    private BooleanExpression categoryEq(Category category) {
이렇게 한 번 수정해봤습니다! 확인부탁드려요! ([923e2cf](https://github.com/f-lab-edu/culture-ticketing/pull/20/commits/923e2cfdab07cd77b5825e9c8d7a6c88e8d6b400))

2023-12-17 13:01 UTC, f-lab-moony approved these changes
고생 많으셨습니다 요건 바로 머지 할게요!

2023-12-17 13:01 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowService.java
> +                .map(show -> ShowResponse.create(show, placeMapByPlaceId.computeIfAbsent(
요 부분은 show가 가지고 있는 placeId 중 하나라도 없으면 터지는걸 의도하시는 것 같은데, 반복문을 돌면서 진행하는 부분이라 잘 안드러나게 되는 것 같아요
유효성검사하는 부분은 그냥 따로 빼는게 어떨까요 ?
아예 메서드 분리를 해도 같은 트랜잭션에서 하니까 쿼리는 두번 안날아갈 것 같아요 ~

추가로, 이렇게 어떤 작업들을 하는지 명시가 되어있으면 선언형의 장점을 잃어버리게 되는데, 메서드 분리를 해서 무엇을 하는지만 드러낼 수 있도록 고민해보시면 좋을 것 같아요!

2023-12-17 13:02 UTC, merged