Feature/issue 5 retrieve show by
f-lab-edu/culture-ticketing pull request #22
Opened 2023-12-29 08:47 UTC by joona95

Issue: #5 

- 공연 상세 조회 기능 추가
  - 기존 service는 id값을 가지고 있어서 연관된 서비스와 해당 도메인 repository만 참조하도록 함
  - 기존 service 내에서 해결 가능한 건 컨트롤러에서 해당 service 참조
  - 기존 service 참조 외에 다른 service 참조가 필요한 경우 순환 참조 오류 해결을 위해 facade service 계층 추가
- 기타 수정
  - 부정연산자 처리 수정
  - 변수 선언 필요 없는 부분 제거
  - 필요 없는 반복문 set 선언으로 제거

2023-12-31 08:28 UTC, f-lab-moony requested changes
고생하셨습니다 ~
ShowFacadeService 관련 피드백에 고쳐야되는 부분인 것 같아서 리뷰 체인지로 돌려둘게요
확인 후 피드백 주세요 ~

2023-12-31 08:28 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        Show show = showService.findShowById(showId);
공연 상세 정보도 공연 목록 만큼이나 트래픽이 몰릴 것 같은 부분이라, 지금은 괜찮지만 나중엔 구조 변경 혹은 조회용 Nosql DB를 따로  다루는 걸 염두에 두는게 좋을 것 같아요 ~

2023-12-31 08:28 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        ShowResponse showDetail = ShowResponse.from(show, place);
요거 어차피 밑에서 합쳐질거라, 여기서는 그냥 ShowDetailResponse.from 을 새로 정의하는게 어떨까요 ?

2023-12-31 08:28 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        Round round = request.toEntity(show);
이거 이상태에선 영속성 컨텍스트에 등록이 안됐을 것 같은데, 밑에 createRoundPerformers에서 find할때 무조건 터지지 않나요 ?

2023-12-31 08:28 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +    public List<RoundWithPerformersResponse> findRoundsByShowId(Long showId) {
요런 모양새가 자주 나오는군요 .. 구조를 한번 더 고민해봐도 좋을 것 같아요

2024-01-02 08:51 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        Round round = request.toEntity(show);
아 이게 이러고 나서 createRound()를 먼저 하고 createRoundPerfomers()를 하니까 createRound()에서 영속성 컨텍스트 등록이 된 것 같아서 이렇게 처리했었어요. 
원래 그래서 createRound()에서 round를 리턴받아서 해당 값으로 처리해야 하나 고민했었어요. 그런데 createRound 시에 영속성 컨텍스트 반영이 될 것 같아서 createRound한 이후에 round 변수를 createRoundPerformers에 전달하니까 roundId가 등록된 값으로 잘 등록되더라구요..!

2024-01-03 15:28 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/PerformerService.java
> +    public void checkShowPerformersExists(Long showId, Set<Long> performerIds) {
수정완료했습니다! ([c6d31ea](https://github.com/f-lab-edu/culture-ticketing/pull/22/commits/c6d31ea53963ca46cee1a2c6f13f36818676c078))

2024-01-03 15:29 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/PerformerService.java
> +                performerIds.remove(performer.getPerformerId());
그렇네요..! 해당 부분 복사한 값 사용하도록 수정했습니다. ([9b05358](https://github.com/f-lab-edu/culture-ticketing/pull/22/commits/9b0535850943f09ef612788518ae904e61764d12))

2024-01-03 15:29 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        ShowResponse showDetail = ShowResponse.from(show, place);
넵 그렇게 하는 게 좋을 것 같아서 수정했습니다. ([d518525](https://github.com/f-lab-edu/culture-ticketing/pull/22/commits/d5185254b04f9f14063c51c934b2accd2a913c8d))

2024-01-03 15:32 UTC, joona95 commented
위에 피드백 주신 내용들 수정할 수 있는 부분들은 수정했습니다.
클라이언트 표시용 x, y 좌표 정보 또한 제거했습니다.
우선 DB 구조 변경 관련 작업은 추후 작업하기로 해서 우선은 수정하지 않았습니다.
영속성 컨텍스트 관련은 실제 실행해보고 문제가 없어서 생각한 방식으로 작동하는 게 맞나보다 하고 진행한 부분이라서 왜 저렇게 작성했는지 코멘트 남겨뒀습니다..! 혹시 제가 잘 못 알고 있는 거라면 말씀주시면 감사하겠습니다..!

2024-01-05 16:53 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
코멘트 하나 더 남겨 놨는데, 확인 부탁드려요 ~
PR은 머지 하겠습니다 ~

2024-01-05 16:53 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowFacadeService.java
> +        Round round = request.toEntity(show);
아 createRound를 바로 하는군요, 이거 이렇게 한꺼번에 하기보다 roundPerformer는 round와 performer가 있는걸 가정하고 동작하는게 맞을 것 같은데 어떻게 생각하시나요 ?

2024-01-05 16:53 UTC, merged