Feature/issue 6 retrieve show calender
f-lab-edu/culture-ticketing pull request #24
Opened 2024-01-06 01:11 UTC by joona95

issue: #6 

<img width="367" alt="스크린샷 2024-01-06 오전 10 03 11" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/938fa99f-e6b1-4b66-b63c-2667f3f38d05">

- 이 화면에서 날짜 선택 시 활성화 시킬 날짜 리스트 전달 API 입니다.
- 해당 공연의 전체 회차 조회 후 존재하는 회차의 날짜 목록을 전달하고자 합니다 
- 컨트롤러를 round 쪽에 둬야할지 show 쪽에 둬야할지에 대한 고민이 좀 있었습니다..! 사용하는 건 round 정보뿐이라서 round에 두는 게 좋지 않을까 싶었는데 공연의 예약 가능 날짜 목록이라서 의미적으로 show가 나은가 싶기도 해서요.

2024-01-13 13:43 UTC, f-lab-moony requested changes
고생하셨습니다! 코멘트 확인 부탁드려요 ~

2024-01-13 13:43 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/RoundService.java
> +    public List<LocalDate> findRoundExistDatesByShowId(Long showId) {
이거는 굳이 LocalDate로 반환해줘야 하나 ? 라는 고민을 해보는게 좋을 것 같은데요
showId에 해당하는 Round 정보의 날짜만 뽑아서 주는 상황인데, 이걸 받아서 쓰는 곳에서 해당 Round들에 대한 정보는 아예 필요가 없을까요 ? 날짜를 보여주고, 해당 날짜에 라운드에 따른 다른 처리를 하게 된다면 Round의 id도 필요하게 될텐데 .. 이런 경우는 그냥 showId에 맞는 Round를 다 넘겨주고 클라이언트에서 원하는대로 쓰는게 맞지 않을까 싶습니다.

클라이언트의 편의성을 생각하는것도 좋지만, 이정도는 클라이언트에서 충분히 컨버팅 해서 쓸 수 있는 정보라고 생각되네요

2024-01-17 06:58 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/RoundService.java
> +    public List<LocalDate> findRoundExistDatesByShowId(Long showId) {
수정 완료했습니다! ([b91ff48](https://github.com/f-lab-edu/culture-ticketing/pull/24/commits/b91ff48805d4eefdc4007eac4d4d05a9d09bc614))

2024-01-17 06:59 UTC, joona95 commented
말씀하신대로 여러 이용 가능하도록 수정했습니다.

- 공연 아이디값으로 회차 목록 조회 기능으로 수정했습니다.
- date 목록 전달이 아니라 회차 정보를 전달하도록 했습니다.
- show controller에서 round controller로 이동했습니다.

2024-01-19 13:53 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요 PR은 바로 머지할게요 ~

2024-01-19 13:53 UTC, merged