Feature/issue 12 create show round performer test
f-lab-edu/culture-ticketing pull request #26
Opened 2024-01-06 04:18 UTC by joona95

issue: #12 

- 이전 PR에서 제시해주신대로 회차 생성과 회차 출연자 목록 생성 기능 분리했습니다. 
  - 기존에는 따로 등록하는 게 오히려 불편하지 않을까 싶어서 했는데 더 생각해보니까 분리하는 게 더 맞을 것 같아서 분리했습니다.
- 회차 생성 테스트 추가
- 회차 출연자 목록 생성 테스트 추가

2024-01-13 14:36 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 코멘트 확인 부탁드려요!

2024-01-13 14:36 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/RoundService.java
> +    protected void checkDuplicatedRoundDateTime(Round round) {
요거 왜 protected일까요 ?

2024-01-13 14:36 UTC, f-lab-moony commented on src/test/groovy/com/culture/ticketing/show/application/RoundServiceTest.groovy
> +        roundService.checkDuplicatedRoundDateTime(round);
요거 테스트떄문에 protected로 빼신 것 같은데, 테스트는 기본적으로 public에 대해서만 작성하고, 내부 메서드는 그걸 사용하는 public 메서드를 통해 검증해요

만약 public 메서드로 검증이 어렵거나 불가능하다면 그건 구조를 다시 고민해 볼 문제고, 그렇게 테스트하기 쉬운 구조로 만들어 나가는게 TDD에요. 테스트를 위해 클래스의 스킴이나 변수 등이 변경이 되어서는 안됩니다 ~

2024-01-17 07:39 UTC, joona95 commented on src/test/groovy/com/culture/ticketing/show/application/RoundServiceTest.groovy
> +        roundService.checkDuplicatedRoundDateTime(round);
해당 부분 private로 다시 변경했습니다! ([f872a78](https://github.com/f-lab-edu/culture-ticketing/pull/26/commits/f872a7838a01b8c14eb4170cc6a30517207038d6))

2024-01-17 07:40 UTC, joona95 commented
- protected로 변경했던 private 함수 원래대로 바꿨습니다. 테스트 내에서 public에서 검사하는 부분 제외하고 제거했습니다.
- 함수명 내에 언더바 들어가있던 부분도 제거했습니다.

2024-01-19 13:54 UTC, f-lab-moony commented
엇 요거 충돌나는데 처리 후 머지 부탁드려요!

2024-01-23 09:41 UTC, merged