Feature/issue 5 shows test
f-lab-edu/culture-ticketing pull request #28
Opened 2024-01-23 12:01 UTC by joona95

- 공연 생성, 조회 테스트 추가
- 출연자 생성 테스트 추가
- 컨틀롤러 400 에러 발생 케이스 parameterized test로 수정

2024-01-23 14:07 UTC, f-lab-moony commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +        1 * performerRepository.save(_)
1 * performerRepository.save(_) >> { args ->
  def request = args[0] as Performer

  request.showId == 1L
}

2024-01-23 14:07 UTC, f-lab-moony commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +        e.message == "출연자 이름을 입력해주세요."
where
showId | performerName || expected
null | "이름" || "공연 아이디를 입력해주세요."
1L || null || "출연자 이름을 입력해주세요."

e.message == expected

2024-01-23 14:07 UTC, f-lab-moony commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +                PerformerFixtures.createPerformer(1L, 1L),
PerformerFixtures.createPerformer(performerId : 1L, showId : 1L)

2024-01-23 14:15 UTC, f-lab-moony commented on src/test/groovy/com/culture/ticketing/show/application/ShowFacadeServiceTest.groovy
> +        roundService.findByShowId(1L) >> List.of(rounds.get(0), rounds.get(1), rounds.get(3))
roundService.findByShowId(1L) >> [
                RoundFixtures.createRound(1L, 1L),
                RoundFixtures.createRound(2L, 1L),
                RoundFixtures.createRound(4L, 1L)
]

2024-01-24 15:01 UTC, f-lab-moony requested changes
거의다 테스트 내용이라 저번 시간에 말씀드린 내용들 말고는 크게 피드백 드릴 부분이 없네요 ㅋㅋ
코멘트 단것만 확인해주세요 ~

2024-01-26 03:27 UTC, joona95 commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +                PerformerFixtures.createPerformer(1L, 1L),
[fb00cb4](https://github.com/f-lab-edu/culture-ticketing/pull/28/commits/fb00cb4148ad212a2227166fbb88b9e22a3242d2) ~ [d77b7b5](https://github.com/f-lab-edu/culture-ticketing/pull/28/commits/d77b7b5c39079068bcb722ac90115dc05ab79389) 에서 map 매개변수 받도록 수정했습니다.

2024-01-26 03:27 UTC, joona95 commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +        e.message == "출연자 이름을 입력해주세요."
해당 부분 수정했습니다. ([84a9f36](https://github.com/f-lab-edu/culture-ticketing/pull/28/commits/84a9f36dd0ceb129189ab1e7b77378b48d8a11e2))

2024-01-26 03:28 UTC, joona95 commented on src/test/groovy/com/culture/ticketing/show/application/PerformerServiceTest.groovy
> +        1 * performerRepository.save(_)
수정했습니다..! ([30db6dd](https://github.com/f-lab-edu/culture-ticketing/pull/28/commits/30db6dde2380ec83a27c6dbe276c7d9c6ca1c2ba))

2024-01-26 03:28 UTC, joona95 commented on src/test/groovy/com/culture/ticketing/show/application/ShowFacadeServiceTest.groovy
> +        roundService.findByShowId(1L) >> List.of(rounds.get(0), rounds.get(1), rounds.get(3))
수정완료했습니다 ([d9c0603](https://github.com/f-lab-edu/culture-ticketing/pull/28/commits/d9c060313eeff57e5ca7c9c4f05f4712de130a50))

2024-01-26 03:31 UTC, joona95 commented
이전에 받은 피드백 관련 반영했습니다..!

- 서비스 내에서만 사용하는 메서드 private으로 수정
- 테스트 내 리스트 표현 List.of 대신 [] 으로 수정
- 생성 서비스 내 arguments 값이 알맞는지 확인 테스트 추가
- fixture에서 map으로 받아서 테스트 시 어떤 값을 넘기는지 확인할 수 있도록 수정
- api request 내부 validation 관련 어노테이션 제거
- 컨트롤러 내 요청값 관련 테스트 제거
- 테스트 내 불필요한 springbean 등록 어노테이션 제거
- 테스트 시 값만 다른 테스트는 where절 이용하도록 수정

2024-01-29 15:45 UTC, f-lab-moony approved these changes
고생하셨습니다!
요거 따로 피드백 드릴건 없을거같아서 바로 머지할게요 ~

2024-01-29 15:55 UTC, f-lab-moony commented
이거 제 프로젝트가 아니라 그런가 소나에서 설정 바꾸거나 할수가 없는 것 같네요
중복검사 룰 제거하시거나 `Suppress` 설정해서 퀄리티 게이트 통과하면 머지 해 주세요 ~
소나 그냥 뺄까 하다가 일단 냅둬보겠습니다 ㅋㅋ

2024-01-30 01:56 UTC, joona95 commented
@SuppressWarnings("Duplicates") 나 @SuppressWarnings("common-java:DuplicatedBlocks")  설정을 해당 클래스에 추가했는데도 효과가 없는데 뭔가 제가 잘 못 설정한 걸까요? sonar 설정을 바꾸려고 하니 setting 관련 항목이 안 보여서 제가 바꿀 수 있는 권한이 있는지 잘 모르겠습니다 ㅠㅠ

2024-01-30 13:50 UTC, merged