Feature/issue 9 create booking
f-lab-edu/culture-ticketing pull request #30
Opened 2024-01-31 13:39 UTC by joona95

Issue: #9 

- 예약 생성 기능 추가
- 예약한 공연 좌석 생성 기능 추가
- 예약한 공연 플로어 생성 기능 추가
- 예약 생성 테스트 추가

2024-02-04 16:33 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 피드백 확인 부탁드려요~

2024-02-04 16:33 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/booking/domain/BookingShowFloor.java
> +public class BookingShowFloor extends BaseEntity {
음? 여기도 층과 좌석이 분리가 되어있군요 .. ? 요거 구조 다시 얘기해보는게 좋을 것 같네요

2024-02-06 09:22 UTC, joona95 commented on src/main/java/com/culture/ticketing/booking/application/BookingFacadeService.java
> +        List<ShowFloor> showFloors = showFloorService.findByIds(bookingShowFloors.stream()
예약하려는 좌석 id값들로만 조회하려고 한 게 맞습니다..! 네이밍을 bookingShowFloors 처럼 bookingShowSeatIds로 바꾸거나 해야 할 것 같네요

2024-02-06 09:34 UTC, joona95 commented on src/main/java/com/culture/ticketing/booking/application/BookingService.java
> +        bookingRepository.save(booking);
아 그러게요 추가하도록 하겠습니다!

2024-02-15 11:54 UTC, joona95 commented
- 예약 좌석 정보를 json 으로 저장하려던 작업 전부터 다시 롤백하여서 진행하였습니다.
- Booking 과 BookingShowSeat, BookingShowFloor 가 연관관계 맺도록 수정했습니다.
- 말씀하신대로 BookingRepository에서 해당 정보 처리하도록 하려했는데 booking의 bookingShowSeats list 에서 예약하려는 좌석 목록 중 하나라도 이미 예약된 게 있는지 확인하려니 좀 애매해져서 BookingShowSeatRepository와 BookingShowFloorRepository 그냥 따로 뺐습니다.
- BookingShowFloorRepository에서 이미 예약됐는지 확인 할 경우 showFloorId와 entryOrder가 동시에 같은 경우를 찾아야 해서 custom repository 통해서 처리했습니다.
- BookingFacadeService는 없애고 BookingService에서 예약 생성 처리하도록 수정했습니다.
- 예약 생성 관련 테스트 수정 및 추가했습니다.

2024-02-16 17:32 UTC, f-lab-moony approved these changes
고생 많으셨습니다~
피드백 좀 남겨뒀는데 확인 부탁드려요!
작업에 크게 영향 있는 부분은 아닌거같아서
요 PR은 이만 머지 하도록 할게요

2024-02-16 17:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/booking/application/BookingService.java
> +        Objects.requireNonNull(request.getUserId(), "유저 아이디를 입력해주세요.");
요런거 유효성검사 메서드로 한번 빼면 좀더 깔끔해질것같아요 ~

2024-02-16 17:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/booking/application/BookingService.java
> +                + showFloorService.getTotalPriceByShowFloorIds(request.getShowFloors().stream()
이거 request 안에 getShowFloorIds 메서드 만들어줘도 좋을 것 같아요 ~

2024-02-16 17:32 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/booking/infra/BookingShowFloorRepositoryCustom.java
> +    boolean existsByShowFloorsInAndBooking_RoundIdAndBooking_BookingStatus(Set<BookingShowFloorSaveRequest> showFloors, Long roundId, BookingStatus bookingStatus);
음 ? 이거 커스텀이면 이름 굳이 이렇게 안지어도 될거같은데요? ㅋㅋ

2024-02-16 17:32 UTC, merged

2024-02-17 23:51 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowFloorService.java
> +                .collect(Collectors.toList());
아 이거 set으로 하려다가 showFloor 같은 경우에는 동일한 걸 입장 순서에 따라 여러 개 가질 수 있을 것 같아서 일부러 중복되도록 하려고 list로 설정한 거 였습니다!