Feature/issue 8 retrieve show seats by round
f-lab-edu/culture-ticketing pull request #34
Opened 2024-02-23 08:51 UTC by joona95

Issue: #8 

- 공연 장소의 구역 목록 조회 기능 추가
- 공연 아이디에 해당하는 등급 목록 조회 기능 추가
- 회차 아이디와 구역 아이디로 공연 좌석 정보 목록 조회 기능 추가
- 관련 테스트 추가
- 이전 PR 코멘트 반영

우선은 ShowFloor 제외하고 ShowSeat 으로 좌석 목록 조회 기능만 추가했습니다.

ShowFloor 개념 자체가 모호해진 것 같아서 우선 따로 작업을 추가하지 않았습니다.

 저번 시간에 나눴던 얘기 바탕으로 좀 더 생각해보고 ShowFloor의 존재에 대한 고민 사항을 밑에 남겨뒀습니다!

=====

<b> 저번 멘토링 시간에 좌석 구조에 대해 얘기를 나눴었는데 이번에 다시 생각해봤는데 멘토님이 말씀하셨던 대로 제가 구조를 잘못 생각했던 것 같아요. </b>

</br>

ShowSeat과 다르게 ShowFloor 라는 개념을 추가했던 건 장소마다 고정된 좌석이 아니라 '공연마다 달라질 수 있는 구역/좌석이라는 의미'로 생각을 했습니다. 그런데 멘토님과 대화 후 생각해봤는데 이 경우도 예약 시 좌석을 선택하는 거라면 사실상 ShowSeat과 다르지 않더라구요.

제가 생각한 개념대로 만들고 싶다면 ShowSeat와 통합을 시켜야 하는 부분인 것 같고, 공연마다 구역 설정을 다르게 하는 걸 추가해야 할 것 같습니다.

ShowFloor를 멘토님하고 마지막에 정의했던대로 먼저 사는 사람이 순서 상관없이 먼저다 라고 하면 Floor라는 개념보다도 예약 방식을 나눠서 입장권 예매의 경우로 생각해야 할 것 같습니다.

같은 공연 예약 내에서 한 곳은 구역 선택만 하면 바로 예약되고, 한 곳은 구역 선택하고 좌석 선택까지 해야하면 예약 과정의 뎁스 차이로 공평성에 문제가 있을 것 같았습니다.

그래서 아예 Show 에서 예약방식 (bookingType) 정보를 가지고 있고 이에 따라 예약 방식을 두 가지로 나누려고 합니다.

</br>

**1. 예약방식 1 - 좌석을 선택해서 예약하는 경우**

<img width="945" alt="스크린샷 2024-02-23 오후 5 07 54" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/62085ab5-ea78-4468-a033-924d44be0df9">

<img width="948" alt="스크린샷 2024-02-23 오후 5 08 02" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/b5f656e7-83db-4e89-9be2-bd266cbf40b3">

<img width="949" alt="스크린샷 2024-02-23 오후 5 08 08" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/e3766c2e-1830-4cb7-b989-8772f597880f">

</br>
</br>

**2. 예약방식 2 - 매수를 선택해서 예약하는 경우**

<img width="940" alt="스크린샷 2024-02-23 오후 5 07 05" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/1ce7925c-f05e-4e23-b04f-c1e951e27759">

</br>
</br>
</br>

**그래서 결론은 이런 식으로 구조를 바꾸는 게 어떨까 하는데 의견을 듣고 싶습니다..!**

<img width="1075" alt="스크린샷 2024-02-23 오후 5 44 56" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/a38faf1c-acd2-4412-a0ee-c391f14692f2">

- 예약방식 1을 초록 네모 안에 있듯이 구현하고자 합니다. 원래 ShowFloor를 만들었던 이유인 '공연마다 달라지는 스탠딩/플로어 등 구역'을 커버하기 위해서 ShowArea를 추가하고자 합니다. 공연마다 새로 만들거나 기존에 있는 Area를 엮을 수 있도록 하는 테이블로 ShowArea를 추가하는 게 어떨까 싶습니다.

- 예약방식 2는 보라 네모 안에 있듯이 구현하고자 합니다. 멘토님이 말씀하셨던 대로 어떤 특정 좌석을 선택하지 않고 구매한 순서와 매수에 따라서만 체크할 수 있도록 하는 건 사실상 입장권 매수 구매 예약 방식이 될 것 같아서요. 이렇게 되면 사실 Floor란 개념은 아니니까 명칭을 수정하고 등급 관련 정보만 조회 가능하면 되지 않을까 싶습니다.

2024-02-25 15:13 UTC, f-lab-moony requested changes
고생 많으셨습니다!
다음 시간에도 구조에 대해서 한번 얘기 해보는게 좋을 것 같네요..!
피드백 확인 부탁드려요!

2024-02-25 15:13 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/show_seat/application/ShowSeatFacadeService.java
> +        BookingShowSeatMapByShowSeatIdResponse bookingShowSeatMapByShowSeatId = new BookingShowSeatMapByShowSeatIdResponse(bookingShowSeatService.findByRoundIdAndShowSeatIds(roundId, showSeatIds));
음 .. 요거 ShowSeat가 예약 여부를 알고 있어도 되지 않나 하는 생각이 좀 드네요?

2024-02-26 09:57 UTC, joona95 commented on src/main/java/com/culture/ticketing/booking/application/dto/BookingShowSeatMapByShowSeatIdResponse.java
> +    private Map<Long, BookingShowSeat> bookingShowSeatMapByShowSeatId;
아하 넵넵 이해했습니다! 이 클래스는 중간에 넘겨주기만 하는 클래스라서 사용하는 api에서는 최종적으로 List<ShowSeatResponse>로 가공해서 넘겨주고 있습니다..!

2024-02-26 10:06 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/application/SeatService.java
> +    public List<Seat> findBySeatIds(List<Long> seatIds) {
아하 넵넵..!! 지금 도메인 넘겨주는 서비스 메서드는 다른 서비스에서 사용하는 경우만 있긴 합니다..! 명확하게 하고 싶으면 추후 서비스를 나누던가 하면 좋을까요?

2024-02-26 11:44 UTC, joona95 commented on src/main/java/com/culture/ticketing/place/infra/AreaRepositoryImpl.java
> +    public List<Area> findByShowId(Long showId) {
area에는 showId가 없어서 그걸 가지고 있는 연관된 테이블이 showSeatGrade다 보니까 저렇게 됐네요.
Area 테이블 ->(areaId)-> Seat 테이블 ->(seatId)-> ShowSeat 테이블 ->(showSeatGradeId)-> ShowSeatGrade 테이블
이렇게 연결하다보니 join이 많이 됐습니다..! ㅠㅠ

2024-02-26 11:53 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/show_seat/application/ShowSeatFacadeService.java
> +        BookingShowSeatMapByShowSeatIdResponse bookingShowSeatMapByShowSeatId = new BookingShowSeatMapByShowSeatIdResponse(bookingShowSeatService.findByRoundIdAndShowSeatIds(roundId, showSeatIds));
ShowSeat는 Show에 연관돼있고 예약은 Round마다 달라서 ShowSeat가 예약 여부를 가질 수가 없어서 예약 정보를 불러와서 체크하게 됐습니다 ㅠㅠ

2024-02-27 14:01 UTC, merged