Feature/add show likes
f-lab-edu/culture-ticketing pull request #39
Opened 2024-04-05 13:11 UTC by joona95

우선은 좋아요 생성 및 삭제 redis에 저장하는 부분 먼저 진행했습니다.

- 이전 spring security, redis 관련으로 PR 코멘트 남겨주신 부분 수정했습니다
  - 모든 리퀘스트 허용 후 블랙리스트 추가되도록 수정
  - 컨트롤러에서 바로 Authentication 받도록 수정 
- 공연 좋아요 생성 및 삭제 기능 추가했습니다
  - 레디스에서 showId(Long) 값을 key값으로 가지고, userId 목록(Set<Long>)을 value값으로 가지도록 했습니다.

질문이 몇가지 있습니다..!
1. 레디스에서 conf 파일 통해서 데이터 저장되도록 설정은 했는데 용량 문제도 있을 거고 RDB나 다른 DB에 저장해야 하지는 않을까요?
2. 만약 그렇다면 레디스에서 가지고 있다가 일정 순간에 DB에 한번에 쓰는 식으로 해결하나요?
3. 나중에 유저가 좋아요한 공연 목록을 보고 싶을 때 key 값은 showId라서 찾기 어려울 것 같은데 이건 어떻게 해결 할 수 있을까요?

2024-04-06 00:14 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백을 좀 남겨뒀는데 확인 부탁드려요!

2024-04-06 00:14 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/common/utils/MailService.java
> +public class MailService {
혹시 메일만 보내는걸로 생각하신걸까요 ?
저번시간에 알람 보내는걸로 얘기 했던거같아서요 ~

2024-04-06 00:14 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/api/ShowController.java
> +        if (authentication != null) {
왜 여기에만 null 처리가 되어있을까요 ?

2024-04-06 00:14 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +        Set<Long> userIds = redisTemplate.opsForValue().get(showId);
요거 레디스에서 카운트 바로 받는거 없나요 ? 있었던거같아서..

2024-04-06 00:14 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +        ValueOperations<Long, Set<Long>> valueOperations = redisTemplate.opsForValue();
레디스에 set 자료구조가 있지 않나요 ? 그거 그냥 쓰면 될거같아서 말씀드려봅니다 ~

2024-04-06 00:14 UTC, f-lab-moony commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +    public void createShowLike(User user, Long showId) {
이거 create나 delete에서 현재 좋아요 수를 넘겨주는건 어떨까요 ?
클라이언트 입장에서 이상태라면 create 혹은 delete 후 count api를 호출해야만 변경된 좋아요 수를 알 수 있어서 api 두 번 호출이 필수적일 것 같은데, 여기서 현재 개수를 넘겨주면 한번으로 줄일 수 있을 것 같아요. 사실상 create나 delete가 count보다 많이 불릴 것 같아서요. count는 처음 리스팅 할때만 보여줄테니까 ..

2024-04-06 00:16 UTC, f-lab-moony commented
>레디스에서 conf 파일 통해서 데이터 저장되도록 설정은 했는데 용량 문제도 있을 거고 RDB나 다른 DB에 저장해야 하지는 않을까요?

용량문제는 어떤걸 말씀하시는걸까요 ? 크게 문제는 없을 것 같긴 한데, 만약 문제가 된다면 RDB나 다른 DB에 저장하는걸로 해결이 안되지 않을까요 ? 문제가 두배로 커질 것 같아요

>만약 그렇다면 레디스에서 가지고 있다가 일정 순간에 DB에 한번에 쓰는 식으로 해결하나요?

뭐 일단 문제가 없을거같긴 하지만 다른 디비에 백업본이 있어야 한다면, 일정주기로 백업 배치같은걸 돌리는게 맞을 것 같아요

>나중에 유저가 좋아요한 공연 목록을 보고 싶을 때 key 값은 showId라서 찾기 어려울 것 같은데 이건 어떻게 해결 할 수 있을까요?

두 세트를 가지고 계시면 될 것 같아요 ? 공연 별 좋아요 한 유저 목록 / 유저 별 좋아요 한 공연 목록

2024-04-06 14:41 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/api/ShowController.java
> +        if (authentication != null) {
공연 정보 조회는 유저가 아니라도 가능한데, 해당 공연 좋아요 여부를 위해서는 또 유저 정보가 필요해서 이렇게 처리했습니다.
authentication이 있는 경우에는 해당 값에서 user 정보를 가져오고, 없는 경우에는 authentication.getPrincipal().getUser() 에서 nullPointerException 나지 않도록 if문 작성했습니다.

2024-04-06 14:46 UTC, joona95 commented on src/main/java/com/culture/ticketing/common/utils/MailService.java
> +public class MailService {
맞아요..! 이거는 그 전에 작업했던 부분으로 남겨뒀던 거고 아직 알람 보내는 것까지 작업을 하지는 않았습니다. 
좋아요 생성/삭제만 우선 레디스로 처리하는 부분만 하고 질문 드리고 수정한 후에 하려고 했었어요..!

2024-04-07 00:27 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +        Set<Long> userIds = redisTemplate.opsForValue().get(showId);
수정했습니다..! [43c3ea9](https://github.com/f-lab-edu/culture-ticketing/pull/39/commits/43c3ea98350b32c584e28bba8e4e9eda7660cb20)

redisTemplate 자체에서는 count하는 건 없는 것 같고 set으로 변경하니까 size 메소드 있어서 사용하도록 했습니다..!

2024-04-07 00:27 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +        ValueOperations<Long, Set<Long>> valueOperations = redisTemplate.opsForValue();
수정했습니다! [43c3ea9](https://github.com/f-lab-edu/culture-ticketing/pull/39/commits/43c3ea98350b32c584e28bba8e4e9eda7660cb20)

2024-04-07 00:27 UTC, joona95 commented on src/main/java/com/culture/ticketing/show/application/ShowLikeService.java
> +    public void createShowLike(User user, Long showId) {
넵 수정했습니다! [ca933d6](https://github.com/f-lab-edu/culture-ticketing/pull/39/commits/ca933d65ab0ed2c72288b894725bb97858a943f4)

2024-04-07 00:40 UTC, joona95 commented
답변 감사합니다..! 
지금은 사실 문제가 없을 것 같은데 어쨌든 redis는 용량 제한이 있어서 좋아요 저장이 많아져서 그걸 넘어서는 순간이 오면 어떻게 하나 궁금해졌었습니다..! 그걸 넘어 서는 순간이 오면 말씀하신대로 배치를 통해서 저장하거나 하는 방식으로 전환하던가 하겠군요.
말씀하신 부분 수정했습니다.


1차로 레디스 사용을 이런식으로 하면 되는지 확인하고 싶어서 '좋아요 생성/삭제' 관련 PR 먼저 했습니다.
젠킨스 배치 부분 작업 다음으로 진행해보겠습니다..!

2024-04-15 14:56 UTC, f-lab-moony commented
뭔가 다 봤던거같은데 머지를 안해뒀었군요 ..! 바로 머지할게요 ~

2024-04-15 14:57 UTC, merged