Feature/jenkins spring batch
f-lab-edu/culture-ticketing pull request #40
Opened 2024-04-28 12:21 UTC by joona95

- 도커에 jenkins, zookeeper, kafka 설정 추가
- 공통 모듈, api 서버, batch 서버로 분리하여 멀티 모듈 프로젝트로 변경
- kafka producer, consumer 추가
- sse 연결 추가
- 배치 서버 내 job, step 추가

2024-05-06 04:26 UTC, f-lab-moony requested changes
고생많으셨습니다!
딱히 고쳐야되는 부분이 있는건 아닌데, 내용 정리 한번만 같이 해보고 머지 하면 좋을 것 같아요 ~

2024-05-06 04:26 UTC, f-lab-moony commented on culture-ticketing-api-server/src/main/java/com/culture/ticketing/notification/application/EmitterService.java
> +        Map<String, SseEmitter> sseEmitters = emitterRepository.findAllEmitterStartWithById(String.valueOf(notification.getUserId()));
userId에 해당하는 emitter가 여러개 있는걸까요 ?

2024-05-06 04:26 UTC, f-lab-moony commented on culture-ticketing-api-server/src/main/java/com/culture/ticketing/notification/application/EmitterService.java
> +        String emitterId = userId + "_" + System.currentTimeMillis();
아이디에 시간이 붙어야하는 이유가 있을까요 ?

2024-05-06 04:26 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/UserService.java
> +public class UserService {
이런 서비스같은것도 공통 모듈로 빼는게 좋지 않을까요 ?

2024-05-06 04:26 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                    producerService.createShowBookingStartNotifications();
이거 한번에 수행되는 양이 얼마나 되나요 ?

2024-05-07 12:01 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                    producerService.createShowBookingStartNotifications();
배치 잡으로 카프카 이벤트 보내는 거 테스트로 할 때는 1시간 남은 공연 데이터 1~2개 생성해서 시도했었습니다.

2024-05-07 12:02 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/UserService.java
> +public class UserService {
일단 메소드가 공통으로 사용하고 있지는 않아서 별개로 userservice, showservice를 배치에 따로 생성했었습니다.
도메인 공통으로 사용하는 서비스들은 공통 모듈로 빼는 게 좋을까요?
카프카, 레디스 같은 configuration들도 공통 모듈로 빼는 게 좋을까요?

2024-05-07 14:26 UTC, merged