Feature/fix batch and sse
f-lab-edu/culture-ticketing pull request #42
Opened 2024-06-04 12:12 UTC by joona95

이전에 피드백 받았던 부분 반영했습니다.
- SSE 연결 시 id값으로 user id 외에 현재 시간 포함될 필요 없을 것 같다고 해서 수정했습니다.
- event cache 맵도 현재 필요하진 않은 듯해서 제거했습니다.
- batch job에서 chunk 하게 이루어지도록 수정했습니다.

질문사항)
- batch job에서 chunk 사용 시 reader, writer를 이런 식으로 사용해도 괜찮을지? 
- kafka consumer는 잘 연결되는 것 같은데 producer 연결에 문제가 있는 것 같은데 이유를 잘 모르겠습니다..!

<img width="894" alt="스크린샷 2024-06-03 오전 12 06 12" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/01b58044-cdf0-4129-b5e3-66dc42e8f7b6">

<img width="796" alt="스크린샷 2024-06-03 오전 12 05 08" src="https://github.com/f-lab-edu/culture-ticketing/assets/39457533/eec84472-2de7-48ce-a3d3-244125f0cd9a">

2024-06-10 16:28 UTC, f-lab-moony requested changes
고생하셨습니다 ~
아래 PR 처리되면 같이 머지할게요 ~

2024-06-10 16:28 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/ProducerService.java
> +        if (userIdsByShowId != null) {
null일때 얼리리턴 하도록 명시해주는건 어떨까요 ?

2024-06-10 16:28 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/ProducerService.java
> +                        .get();
요건 뭐죠 ?

2024-06-10 16:28 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                .queryString("select s from Show s " +
오 이거 왜 쿼리스트링 쓰셨나요 ?

2024-06-10 16:28 UTC, f-lab-moony commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                    producerService.createShowBookingStartNotifications(show);
벌크로 수행하는 방법은 없을까요 ?

2024-06-11 11:18 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/ProducerService.java
> +                        .get();
공연 좋아요를 한 유저 목록에 예약시작알림 보내기 위해 이벤트보내는 부분입니다..!

2024-06-11 11:20 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                .queryString("select s from Show s " +
1시간 남은 공연 목록 조회할 때 chunk하게 가져오고 싶었습니다. 그래서 기존에 jpa 사용하는 부분을 어떻게 해야하나 했는데 jpa 에서 paging 기능 사용하는 item reader가 따로 있다고 해서 그걸 사용하려고 예시 참고해서 작성했습니다. JpaPagingItemReader를 사용하는게 아닐까요?

2024-06-11 11:23 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/config/BatchConfig.java
> +                    producerService.createShowBookingStartNotifications(show);
사실 그래서 뭔가 kafkaItemWriter 같은 게 있나 하고 찾아보다가 잘 모르겠더라구요 ㅠㅠ .. reader에서는 Jpa를 쓰고 writer에서는 kafka를 쓰는게 가능할까요? 아니면 좀 스텝에 분리가 필요한걸까요?

2024-06-13 07:19 UTC, joona95 commented on culture-ticketing-batch-server/src/main/java/com/culture/ticketing/application/ProducerService.java
> +                        .get();
get을 사용했던 이유가 get()을 사용하지 않으면 kafka에 publish가 다 완료되기 전에 배치 서버가 종료돼서 그렇게 했었습니다!

2024-06-13 13:07 UTC, joona95 commented
앞에 요청한 PR merge까지 해서  요청드립니다.
AbstractItemReader 활용하도록 수정했습니다.
kafka 연결 안되던 거 docker와 localhost 가 별도로 요청이 들어가서 config 설정에 문제가 있어서 그랬던 것 같습니다. 해당 부분도 수정완료했습니다.

2024-06-22 04:53 UTC, f-lab-moony approved these changes
고생 많으셨습니다 PR은 머지해둘게요 ~

2024-06-22 04:53 UTC, f-lab-moony commented on culture-ticketing-core/src/main/java/com/culture/ticketing/show/domain/ShowOrderBy.java
> +    public static OrderSpecifier getOrderSpecifier(ShowOrderBy orderBy) {
요걸 이렇게 static으로 빼는것보다 각 enum의 요소에 메서드를 만드는게 어떨까요 ?

2024-06-22 04:53 UTC, merged